# Generated by Django 4.2.15 on 2025-03-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysfortest', '0004_alter_student_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='best_time',
            field=models.IntegerField(default=0),
        ),
    ]
