# Generated by Django 4.2.15 on 2025-04-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysfortest', '0005_student_best_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='best_time',
            field=models.IntegerField(default=1000),
        ),
    ]
